code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.debugpy
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension ms-azuretools.vscode-docker
code --install-extension pkief.material-icon-theme
code --install-extension prisma.prisma
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension ms-ceintl.vscode-language-pack-ko